version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ../mongoDB:/data/db
    networks:
      - default
    ports:
      - 27017:27017
  
  app:
    depends_on:
      - mongodb
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: ./.env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://root:root@mongodb:27017/
    stdin_open: true
    tty: true
    networks:
      - default
  

networks:
  default:
    name: express-app
    external: true